### ISSUE TITLE
(BUG) Pop-up doesn't close after the purchase of any additional service

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/account.ecommerceberlin.com#17]
I just wanted to let you know about a bug although I know it might not apply to nextgen. 

expected result
Pop-up should close after clicking on the "buy now" button. 

actual result
Pop-up stays open resulting in exhibitors pressing it multiple times = ordering multiple services instead of one
![changestatus?token=42ce3d1cd3d012a826583a898b535201e0109991 2022-03-08 17-47-34](https://user-images.githubusercontent.com/75311923/157285171-e911038d-1516-459e-83c7-fd770688c4de.png)

steps to reproduce
enter any exhibitors profile / open add services section / purchase any additional service / click on the "buy now" button

proof
![Screenshot 2022-02-25 at 14 39 26](https://user-images.githubusercontent.com/75311923/157285080-d2d48b20-bce7-4756-a412-ee24a01740fc.png)

Severity/Priority
Minor - from the IT side
Major - from the AM side - we need to contact every company and clarify how many items they intended to order

number of users already affected (reporting this issue) of total users
>10

team members who tested (apart from creator of bug report)
GY, DK

**Comment by az** [comment]
@jprzybylski4 inspecting....

**Comment by az** [comment]
test no 1 

![E-commerce Berlin Expo 🔊 2022-03-08 20-21-14](https://user-images.githubusercontent.com/2198/157309831-4d6f5f73-d994-4035-8319-ede2ad3c1a42.jpg)

**Comment by az** [comment]
test no 2 (flyers)

![E-commerce Berlin Expo 🔊 2022-03-08 20-24-39](https://user-images.githubusercontent.com/2198/157310271-60b4965c-4a8f-4fa3-b28a-cfd2fbd234cd.jpg)

**Comment by az** [comment]
@jprzybylski4 please PERSONALLY test all bugs before placing them here 

if something does not work - check tickets first (LIMITS, MAX (max bookable pcs per client), DATES)

**Comment by az** [comment]
and "PROOF" ?

provided screenshot (DISPLAY) concerns the item that was previously reported by me 

https://fp20.slack.com/archives/C01Q00HA4CT/p1646396224369909

and i advised to FIX it or REMOVE it ....
