### ISSUE TITLE
(BUG) Removed representatives are still visible on the exhibitor's profile

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/account.ecommerceberlin.com#18]
environment 
Chrome 

expected result
After the representative is deleted from the list on the exhibitor's profile it should not be shown on the list anymore. 

actual result
The representative is properly deleted from admin but still shown on the list on the exhibitor's profile.

steps to reproduce
Open exhibitor's profile / open Company representatives section / click on the "delete" button next to the representative

proof
Screencast linked on Slack

Severity/Priority
Minor 

number of users already affected (reporting this issue) of total users
2 

team members who tested (apart from creator of bug report)
DK

**Comment by az** [comment]
@jprzybylski4 fixed.
