### ISSUE TITLE
Reveal "add party representatives" on the Exhibitor's Profile

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/account.ecommerceberlin.com#19]
I believe we're missing a ticket in the system. 
We used to have two tickets - one for paid registration, one for the free registration. 
Could you please clone the ticket so I can set it up?

**Comment by jprzybylski4** [comment]
Just fyi - I've tested it on the EBE profile - there's a connection error when you try to register a new representative
![Monosnap 2022-03-25 18-48-30](https://user-images.githubusercontent.com/75311923/160174863-42b7d596-64e0-49e6-9b64-6573135047e5.png)

**Comment by az** [comment]
@jprzybylski4 its because - you have "stolen" a ticket so there is not ticket with role "party" ... what is the strategy here? there should be 2 types of tickets? free and paid?

**Comment by jprzybylski4** [comment]
Yes - I guess we must've used it for sth else in the meantime.
The strategy is the same - the registration via "add party representatives" in expojuicer should use a free ticket.
The paid tickets should be added by the Account Managers if the company registers more reps than they have in the package. 

So 2 tickets - free and paid.

**Comment by az** [comment]
@jprzybylski4 OK....it seemed strange to me that there are some paid tickets already booked....
