### ISSUE TITLE
update newsletter files 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/account.ecommerceberlin.com#20]
please send me updated 2 first files

https://github.com/eventjuicer/services/tree/master/resources/views/emails/exhibitor

**Comment by jprzybylski4** [comment]
Updated files attached. I wasn't sure how to change the old logotype with a photo.
Just in case - we want to use this photo: 
https://res.cloudinary.com/ecommerceberlin/image/upload/v1648205241/6_get_your_ticket_646x220.png

[Promoninja-newsletter.zip](https://github.com/ecommerceberlin/account.ecommerceberlin.com/files/8352360/Promoninja-newsletter.zip)

**Comment by az** [comment]
b013832c1e40f130041ffde9b53cf99c3913f423

**Comment by az** [comment]
updated
