### ISSUE TITLE
Reveal rewards, promo materials, browse participants, RSVPs modules

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/account.ecommerceberlin.com#23]
Meeting scheduler tested. 
Rewards are checked. Ranking needs the last build and will be fine. 
I just couldn't test promoninja points and ranking but I hope they work fine.

**Comment by az** [comment]
"Meeting scheduler tested." how have you tested this @jprzybylski4 ? 
i cannot see the list of visitors - got no results msg.

ranking to be fixed as well.

many tasks to do - thats why i really hate 2 parallel versions.

**Comment by jprzybylski4** [comment]
@az I've sent 3 invites to myself. All of them seemed to work. Also meeting scheduler seems to work fine on EBE test profile. 
Proof below: 
![meetings3](https://user-images.githubusercontent.com/75311923/162287730-b44e427f-3b55-415a-b767-31f2c768964e.png)
![meetings2](https://user-images.githubusercontent.com/75311923/162287741-0c9c83f7-123f-4948-8cc9-ea6b074bc9df.png)
![meetings4](https://user-images.githubusercontent.com/75311923/162287778-c37101b2-4645-414f-8576-5f2b9e3a6c0e.png)
![meetings1](https://user-images.githubusercontent.com/75311923/162287808-52dc521a-77bb-4785-acd0-5434c12ea096.png)
![meetings5](https://user-images.githubusercontent.com/75311923/162287943-7ef72c55-cae9-4a43-952d-c3a2f6a5f0ca.png)

**Comment by az** [comment]
@jprzybylski4 thx... i see it working now too

**Comment by az** [comment]
@jprzybylski4 ranking fixed (uses new promoninja points counting method) - it catches also natural traffic - from earlier, exhibitors' activities (as no utm_ in links are needed...)

**Comment by az** [comment]
@jprzybylski4 ok, above-mentioned modules enabled. check it out. (ranking shows up on EBE test account but i cannot see it on random exh account....maybe the weather...)

**Comment by az** [comment]
ok, it was not enabled in the settings... now all seems to work @jprzybylski4

**Comment by jprzybylski4** [comment]
Thanks - I was just about to confirm that now it loads on the exhibitors profiles as well!
